# Generated by Django 6.0.3 on 2026-03-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereport',
            name='leave_days',
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='absent_with_reason',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='nfd_days',
            field=models.IntegerField(default=0, verbose_name='No Full Day / Half Days'),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='working_leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('WORKING_LEAVE', 'Work From Home'), ('NFD', 'No Full Day / Half Day'), ('LATE', 'Late')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee', 'attendance_date'], name='attendance__employe_37ed17_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_date', 'status'], name='attendance__attenda_f3ac94_idx'),
        ),
    ]
