# Generated by Django 6.0.3 on 2026-03-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendancereport_leave_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='absent_with_reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='generated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='working_leave_days',
            field=models.IntegerField(),
        ),
    ]
